#!/usr/bin/env python3
"""Generate Vibeshine's deterministic HDR10 virtual-monitor EDID header."""

from __future__ import annotations

import argparse
from pathlib import Path


BASE_TEMPLATE = bytes.fromhex(
    "00 ff ff ff ff ff ff 00 1e 6d c8 c0 01 01 01 01 "
    "01 20 01 03 80 a0 5a 78 0a ee 91 a3 54 4c 99 26 "
    "0f 50 54 a1 08 00 31 40 45 40 61 40 71 40 81 80 "
    "d1 c0 01 01 01 01 08 e8 00 30 f2 70 5a 80 b0 58 "
    "8a 00 40 84 63 00 00 1e 6f c2 00 a0 a0 a0 55 50 "
    "30 20 35 00 40 84 63 00 00 1e 00 00 00 fd 00 18 "
    "78 1e ff 77 00 0a 20 20 20 20 20 20 00 00 00 fc "
    "00 4c 47 20 54 56 20 53 53 43 52 32 0a 20 01 64"
)


def checksum(block: bytearray) -> None:
    block[127] = (-sum(block[:127])) & 0xFF


def build_edid() -> bytes:
    base = bytearray(BASE_TEMPLATE)
    # Manufacturer "VBS", product 1, and a deterministic virtual serial.
    base[8:10] = bytes((0x58, 0x53))
    base[10:12] = bytes((0x01, 0x00))
    base[12:16] = bytes((0x01, 0x00, 0x00, 0x00))
    base[21:23] = bytes((60, 34))
    # Keep both detailed timings consistent with the base-block 600x340 mm
    # image size. The donor timings otherwise encode an unrelated 1600x900 mm
    # panel and cause compositors to infer surprising scale factors.
    base[66:69] = bytes((0x58, 0x54, 0x21))
    base[84:87] = bytes((0x58, 0x54, 0x21))
    base[113:126] = b"Vibeshine HDR"
    base[126] = 1
    checksum(base)

    cta = bytearray(128)
    cta[0] = 0x02  # CTA-861 extension
    cta[1] = 0x03
    data_blocks = bytes(
        (
            0x44,  # Four short video descriptors.
            97,  # 3840x2160p60 (the base-block DTD is already preferred)
            118,  # 3840x2160p120
            16,  # 1920x1080p60
            63,  # 1920x1080p120
            0xE3,
            0x05,
            0xC0,
            0x00,  # BT.2020 RGB and YCbCr colorimetry
            0xE6,
            0x06,
            0x0D,  # SDR, SMPTE ST 2084 PQ, and HLG EOTFs
            0x01,  # HDR static metadata type 1
            0x8A,  # Approximately 1,000 nit desired maximum luminance
            0x72,  # Approximately 590 nit desired max-frame-average luminance
            0x01,  # Low black level
        )
    )
    cta[2] = 4 + len(data_blocks)
    cta[3] = 0
    cta[4 : 4 + len(data_blocks)] = data_blocks
    checksum(cta)
    return bytes(base + cta)


def header(edid: bytes) -> str:
    rows = []
    for offset in range(0, len(edid), 12):
        values = ", ".join(f"0x{value:02x}" for value in edid[offset : offset + 12])
        rows.append(f"  {values},")
    return (
        "/* Generated by generate_hdr_edid.py; do not edit manually. */\n"
        "#ifndef VIBESHINE_HDR_EDID_H\n"
        "#define VIBESHINE_HDR_EDID_H\n\n"
        "static const unsigned char vibeshine_hdr_edid[] = {\n"
        + "\n".join(rows)
        + "\n};\n"
        "static const unsigned int vibeshine_hdr_edid_len = sizeof(vibeshine_hdr_edid);\n\n"
        "#endif\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--header", type=Path)
    parser.add_argument("--binary", type=Path)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()
    edid = build_edid()
    generated = header(edid)
    if args.check and args.check.read_text(encoding="utf-8") != generated:
        raise SystemExit(f"{args.check} is not generated from this script")
    if args.header:
        args.header.write_text(generated, encoding="utf-8")
    if args.binary:
        args.binary.write_bytes(edid)
    if not args.header and not args.binary and not args.check:
        print(generated, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
