# SPDX-License-Identifier: GPL-2.0-only
vibeshine_drm-y := \
	vkms_drv.o \
	vkms_plane.o \
	vkms_output.o \
	vkms_formats.o \
	vkms_crtc.o \
	vkms_composer.o \
	vkms_writeback.o \
	vkms_connector.o \
	vkms_config.o \
	vkms_configfs.o \
	vkms_colorop.o \
	vkms_luts.o

obj-m += vibeshine_drm.o
