#!/usr/bin/env python3

import pathlib
import sys


def require(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise AssertionError(f"{label} is missing required contract: {needle}")


root = pathlib.Path(sys.argv[1])
service = (root / "packaging/linux/vibeshine.service").read_text()
prepare_service = (root / "packaging/linux/vibeshine-machine-prepare.service").read_text()
host = (root / "packaging/linux/vibeshine-machine-host").read_text()
handoff = (root / "packaging/linux/vibeshine-session-handoff").read_text()
launcher = (root / "packaging/linux/vibeshine-session-exec.c").read_text()
private_display = (root / "src/platform/linux/private_display.cpp").read_text()
audio = (root / "src/platform/linux/audio.cpp").read_text()
nvhttp = (root / "src/nvhttp.cpp").read_text()
sysusers = (root / "packaging/linux/vibeshine.sysusers").read_text()
apps = (root / "packaging/linux/prelogin/apps.json").read_text()
packaging = (root / "cmake/packaging/linux.cmake").read_text()
root_cmake = (root / "CMakeLists.txt").read_text()
arch_install = (root / "packaging/linux/Arch/vibeshine.install").read_text()
rpm = (root / "packaging/linux/copr/Sunshine.spec").read_text()
postinst = (root / "packaging/linux/vibeshine-postinst.in").read_text()
prerm = (root / "packaging/linux/vibeshine-prerm.in").read_text()
special_packaging = (root / "cmake/prep/special_package_configuration.cmake").read_text()
drm_setup = (root / "third-party/libvirtualdisplay/linux/packaging/vibeshine-drm-setup.service.in").read_text()
kwin_refresh = (root / "packaging/linux/vibeshine-kwin-capability-refresh.service").read_text()
kwin_watch = (root / "packaging/linux/vibeshine-kwin-capability.path").read_text()

require(sysusers, 'u vibeshine - "Vibeshine machine host" /var/lib/vibeshine /usr/bin/nologin', "sysusers")
require(service, "User=vibeshine", "machine service")
require(service, "Group=vibeshine", "machine service")
require(service, "StateDirectory=vibeshine", "machine service")
require(service, "StateDirectoryMode=0700", "machine service")
require(service, "vibeshine-machine-host run", "machine service")
require(service, "DevicePolicy=closed", "machine service")
require(service, "DeviceAllow=char-drm rw", "machine service")
require(service, "DeviceAllow=/dev/uinput rw", "machine service")
require(service, "vibeshine-machine-host cleanup", "machine service")
if "User=root" in service or "CAP_DAC_OVERRIDE" in service:
    raise AssertionError("machine host must not run as root or bypass filesystem permissions")
require(prepare_service, "Type=oneshot", "prepare service")
require(prepare_service, "vibeshine-machine-host prepare", "prepare service")
require(prepare_service, "ReadOnlyPaths=/home", "prepare service")
require(prepare_service, "InaccessiblePaths=/root", "prepare service")
if "WantedBy=" in prepare_service:
    raise AssertionError("privileged preparation must run only as a dependency of the machine host")

require(host, "readonly machine_profile=/var/lib/vibeshine", "machine host")
require(host, "source=$desktop_home/.config/vibeshine", "one-time migration")
require(host, "profile is non-empty without its marker", "one-time migration")
require(host, 'chown "$service_user:$service_user" "$machine_profile"', "machine profile ownership")
require(host, 'chmod 0700 "$machine_profile"', "machine profile mode")
require(host, 'setfacl -m "u:$service_user:--x" "$runtime"', "runtime socket boundary")
require(host, 'setfacl -x "u:$service_user"', "runtime ACL cleanup")
require(host, 'chmod 0640 "$temporary"', "trusted session record")
require(host, 'VIBESHINE_MACHINE_HOST=1', "child-launch routing")
require(host, "read_allowed_clients", "pre-login client policy")
require(host, "VIBESHINE_ALLOWED_CLIENT_UUIDS", "pre-login client policy")
require(host, "authorize_commands", "administrator command authorization")
require(host, "session-commands", "administrator command manifest")
require(host, '"HOME=$session_home"', "desktop integration home")
require(host, "/usr/bin/setpriv --reuid", "non-PAM session transition")
if "/usr/bin/runuser" in host:
    raise AssertionError("restricted machine preparation must not invoke PAM through runuser")

require(launcher, 'static const char session_path[] = "/run/vibeshine/session.env"', "session launcher")
require(launcher, "O_NOFOLLOW", "session launcher")
require(launcher, "attributes.st_uid != 0", "session launcher")
require(launcher, "attributes.st_gid != service_gid", "session launcher")
require(launcher, "setgroups(identity->group_count", "session launcher")
require(launcher, "setgid(identity->gid)", "session launcher")
require(launcher, "setuid(identity->uid)", "session launcher")
require(launcher, "cap_init()", "session launcher")
require(launcher, "PR_SET_NO_NEW_PRIVS", "session launcher")
require(launcher, "command_is_authorized", "session launcher")
require(launcher, "command_manifest_path", "session launcher")
require(launcher, "clearenv()", "session launcher")
require(launcher, '"kscreen"', "fixed KScreen verb")
require(launcher, '"pactl"', "fixed audio verb")
require(launcher, '"steam"', "fixed Steam verb")
require(launcher, '"lutris"', "fixed Lutris verb")
require(launcher, 'char *const shell_argv[] = {"/bin/sh", "-c", argv[2]', "authorized app shell")
if "execvp(" in launcher:
    raise AssertionError("session launcher must not accept an unrestricted executable path")
require(private_display, 'std::getenv("VIBESHINE_MACHINE_HOST")', "KScreen routing")
require(private_display, 'owned_argv.emplace_back("/usr/libexec/vibeshine/vibeshine-session-exec")', "KScreen routing")
require(private_display, 'owned_argv.emplace_back("kscreen")', "KScreen fixed verb")
require(audio, 'std::getenv("VIBESHINE_MACHINE_HOST")', "session audio routing")
require(audio, 'constexpr auto session_exec_path = "/usr/libexec/vibeshine/vibeshine-session-exec"', "session audio boundary")
require(audio, 'arguments.insert(arguments.begin(), "pactl")', "session audio control")
require(audio, '"parec"', "session audio capture")
if "system(" in audio or "/bin/sh" in audio:
    raise AssertionError("session audio bridge must not invoke a shell")

require(handoff, "readonly host_service=vibeshine.service", "session handoff")
require(handoff, "/usr/bin/setpriv --reuid", "non-PAM handoff")
if "/usr/bin/runuser" in handoff:
    raise AssertionError("session handoff must not invoke PAM through runuser")
require(handoff, 'write_state_file "$marker_directory" "$desktop_user" "$desktop_uid" "$token" 0600', "session handoff")
if "user_systemctl \"$desktop_user\" start" in handoff:
    raise AssertionError("handoff must restart the machine service, not a per-user host")
require(apps, "vibeshine-machine-host activate", "pre-login desktop app")

require(packaging, "add_executable(vibeshine_session_exec", "native packaging")
require(packaging, "vibeshine-machine-host", "native packaging")
require(packaging, "vibeshine.service", "native packaging")
require(packaging, "vibeshine.sysusers", "native packaging")
require(packaging, "cap_setgid,cap_setuid+ep", "native packaging")
if '"${CMAKE_SOURCE_DIR}/packaging/linux/vibeshine-prelogin.service"' in packaging:
    raise AssertionError("native package must not install the copied-profile pre-login service")

require(arch_install, "setcap cap_setgid,cap_setuid=ep", "Arch package")
require(arch_install, "chown root:vibeshine", "Arch package")
require(arch_install, "systemctl enable vibeshine.service", "Arch package")
require(arch_install, "local helper=/usr/libexec/vibeshine/vibeshine-kwin-capability", "Arch package")
require(arch_install, '"$helper" prepare', "Arch package")
require(arch_install, "/usr/libexec/vibeshine/vibeshine-kwin-capability restore", "Arch package")
require(postinst, "@VIBESHINE_PRIVILEGED_LIBEXEC_INSTALL_DIR@/vibeshine-kwin-capability", "native post-install")
require(prerm, "@VIBESHINE_PRIVILEGED_LIBEXEC_INSTALL_DIR@/vibeshine-kwin-capability", "native pre-remove")
require(packaging, "vibeshine-kwin-capability.path", "native packaging")
require(postinst, "enable --now vibeshine-kwin-capability.path", "native post-install")
require(prerm, "disable --now vibeshine-kwin-capability.path", "native pre-remove")
require(kwin_watch, "PathChanged=/usr/bin/kwin_wayland", "KWin replacement watcher")
require(kwin_refresh, "vibeshine-kwin-capability prepare", "KWin replacement refresh")
require(nvhttp, "greeter_client_allowed", "TLS pre-login client gate")
require(special_packaging, "if(BUILD_VIBESHINE_KWIN_GPU_BRIDGE)", "package configuration")
require(special_packaging, "VIBESHINE_PRIVILEGED_LIBEXEC_INSTALL_DIR}/vibeshine-kwin-capability prepare", "package configuration")
bridge_setting = "set(BUILD_VIBESHINE_KWIN_GPU_BRIDGE ON CACHE BOOL"
special_include = "include(${CMAKE_MODULE_PATH}/prep/special_package_configuration.cmake)"
require(root_cmake, bridge_setting, "top-level package configuration")
require(root_cmake, special_include, "top-level package configuration")
if root_cmake.index(bridge_setting) > root_cmake.index(special_include):
    raise AssertionError("KWin GPU bridge must be enabled before package templates are configured")
require(drm_setup, "@VIBESHINE_KWIN_CAPABILITY_EXEC_START@", "DRM setup service")
require(drm_setup, "@VIBESHINE_KWIN_CAPABILITY_EXEC_STOP@", "DRM setup service")
require(drm_setup, "@VIBESHINE_KWIN_CAPABILITY_REMAIN_AFTER_EXIT@", "DRM setup service")
require(rpm, "%caps(cap_setgid,cap_setuid=ep)", "RPM package")
require(rpm, "vibeshine-kwin-capability prepare", "RPM package")
require(rpm, "vibeshine-kwin-capability restore", "RPM package")
require(rpm, "%{_unitdir}/vibeshine.service", "RPM package")
require(rpm, "%{_unitdir}/vibeshine-kwin-capability.path", "RPM package")

print("PASS: least-privilege Linux machine service contract")
